<?php

namespace MiguelAlcaino\MindbodyPaymentsBundle\Repository;

/**
 * CustomerSubscriptionStatusChangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerSubscriptionStatusChangeRepository extends \Doctrine\ORM\EntityRepository
{
}
