<?php

namespace MiguelAlcaino\MindbodyPaymentsBundle\Repository;

use MiguelAlcaino\MindbodyPaymentsBundle\Entity\CustomerSubscription;
use MiguelAlcaino\MindbodyPaymentsBundle\Entity\TransactionRecord;

/**
 * CustomerSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns the last transaction record linked to this subscription
     * @param CustomerSubscription $customerSubscription
     * @return TransactionRecord|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getLastTransactionRecord(CustomerSubscription $customerSubscription)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('tr')
            ->from(TransactionRecord::class, 'tr')
            ->where('tr.customerSubscription = :customer_subscription')
            ->setParameter('customer_subscription', $customerSubscription)
            ->orderBy('tr.created', 'DESC')
            ->setMaxResults(1)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
