<?php

namespace MiguelAlcaino\MindbodyPaymentsBundle\Repository;

/**
 * TransactionItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionItemRepository extends \Doctrine\ORM\EntityRepository
{
}
